List<Map<String, dynamic>> places = [
  {
    "id": 7050,
    "name": "Furious Place",
    "place_name": "Most Furious Place and Peaceful natural place",
    "content": "Nature captions fro photos, short nature captions, natural beauty quotes for Instagram, Instagram bio for nature lover: Nothing is as beautifil and refreshing as nature! As we are always ready for outdoor adventures.",
    "img1": "assets/images/1.jpg",
    "img2": "assets/images/11.jpg",
    "img3": "assets/images/21.jpg",
  },
  {
    "id": 7051,
    "name": "Luxury Place",
    "place_name": "Most Luxury Place and Peaceful natural place",
    "content": "Nature captions fro photos, short nature captions, natural beauty quotes for Instagram, Instagram bio for nature lover: Nothing is as beautifil and refreshing as nature! As we are always ready for outdoor adventures.",
    "img1": "assets/images/2.jpg",
    "img2": "assets/images/12.jpg",
    "img3": "assets/images/22.jpg",
  },
  {
    "id": 7052,
    "name": "Favorite Place",
    "place_name": "Most Favorite Place and Peaceful natural place",
    "content": "Nature captions fro photos, short nature captions, natural beauty quotes for Instagram, Instagram bio for nature lover: Nothing is as beautifil and refreshing as nature! As we are always ready for outdoor adventures.",
    "img1": "assets/images/3.jpg",
    "img2": "assets/images/13.jpg",
    "img3": "assets/images/23.jpg",
  },
  {
    "id": 7053,
    "name": "Nature Look",
    "place_name": "Most Natural Place and Peaceful natural place",
    "content": "Nature captions fro photos, short nature captions, natural beauty quotes for Instagram, Instagram bio for nature lover: Nothing is as beautifil and refreshing as nature! As we are always ready for outdoor adventures.",
    "img1": "assets/images/4.jpg",
    "img2": "assets/images/14.jpg",
    "img3": "assets/images/24.jpg",
  },
];